# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a24ab399a0870af3ce81600ff922d6bece497f2e2369b67c2ef31f071f726db472eeaa561555996a5cd171e42fd92cc775593ef146c41e4bb6671af87a9c5e2

test:
  secret_key_base: f27ee639f569a0556cd29b023f8b7ba48f4577b5f9a1badfdbd467c1c34641f31edfe481329681ae66dc78e7e1f95b644f58f153334f480b2c80ad75b8c221b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
